### PR TITLE
Use fmt::Display in InitError.

### PR DESCRIPTION
**Pull request by csherratt**
Revert change to use .ok().except(...)

In response to @tomaka's comment on https://github.com/bjz/glfw-rs/pull/280#issuecomment-71368742.

### CODE REVIEW

**Comment by penberg** [comment]
Can you please also revert 47906f8160e3035fc1a5dc27c8335b5c8ad2f6bd that updated README?

**Comment by csherratt** [comment]
oops, missed that one.

**Comment by tomaka** [comment]
Apparently they changed it again in Rust master, and you will need to implement `Debug` instead of `Display` :( The change will be visible in tomorrow's nightlies.
But it's just a simple rename, so it will be easy to fix.

**Comment by csherratt** [comment]
Show is already implemented, so we will just have to Replace every Show with Debug. Thanks for the heads up tomaka.

**Comment by bjz** [comment]
Waa - what is the difference between Display and Debug?

**Comment by tomaka** [comment]
`println!("{}", a)` uses `Display` and `println!("{:?}", a)` uses `Debug`.

`Debug` means "show the value" while `Display` means "turn the value into a string".
For example if you have a `enum Token { LeftParenthesis }`, I think that implementing `Display` should print `(` and `Debug` should print `Token::LeftParenthesis`.

**Comment by bjz** [comment]
Oh ok, makes sense that this was fixed. And yes, I am glad for the `Debug`/`Display` distinction now

**Pull request merged**
